(() => {
  const toast=(message,type='success')=>{let box=document.querySelector('[data-toast]');if(!box){box=document.createElement('div');box.dataset.toast='';document.body.append(box)}box.className=`toast fixed bottom-5 right-5 z-[100] max-w-[calc(100vw-40px)] rounded-xl px-5 py-4 text-sm font-semibold text-white shadow-xl ${type==='error'?'bg-red-600':'bg-slate-900'}`;box.textContent=message;clearTimeout(window._toastTimer);window._toastTimer=setTimeout(()=>box.remove(),4200)};
  window.FixMart={toast,save:(key,value)=>{const arr=JSON.parse(localStorage.getItem(key)||'[]');arr.push(value);localStorage.setItem(key,JSON.stringify(arr))},ref:()=>`FM-${Date.now().toString().slice(-7)}`};
  const localPhotos={
    '1504148455328-c376907d081c':'shop-workbench-01.jpg','1581092160562-40aa08e78837':'tools-workbench-01.jpg','1586864387967-d02ef85d93e8':'tools-hand-01.jpg','1607472586893-edb57bdc0e39':'plumbing-fittings-01.jpg','1558008258-3256797b43f3':'electrical-fittings-01.jpg','1581092921461-eab62e97a780':'workshop-supplies-01.jpg','1530124566582-a618bc2615dc':'metal-tools-01.jpg','1581235720704-06d3acfcb36f':'screwdriver-tools-01.jpg','1558618666-fcd25c85cd64':'copper-wire-01.jpg','1518770660439-4636190af475':'electronic-parts-01.jpg','1519389950473-47ba0277781c':'workshop-team-01.jpg','1516321318423-f06f85e504b3':'technician-01.jpg','1581092580497-e0d23cbdf1dc':'workshop-machinery-01.jpg','1581092335878-2d9ff86ca2bf':'industrial-tools-01.jpg','1581091226825-a6a2a5aee158':'fasteners-01.jpg','1567789884554-0b844b597180':'workshop-hardware-01.jpg','1581092160607-ee22621dd758':'tools-repair-01.jpg','1581092918056-0c4c3acd3789':'metal-workshop-01.jpg','1581092795360-fd1ca04f0952':'construction-tools-01.jpg','1581092334651-ddf26d9a09d0':'cable-fittings-01.jpg','1581092162384-8987c1d64718':'plumbing-work-01.jpg','1597733336794-12d05021d510':'technician-workshop-01.jpg','1621905251189-08b45d6a269e':'electrician-work-01.jpg'
  };
  function localizeImages(root=document){root.querySelectorAll('img[src*="images.unsplash.com"]').forEach(img=>{const id=img.src.match(/photo-([a-zA-Z0-9-]+)/)?.[1];if(localPhotos[id])img.src=`assets/images/${localPhotos[id]}`})}
  document.addEventListener('submit',e=>{const form=e.target.closest('[data-local-form]');if(!form)return;e.preventDefault();if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form).entries());data.reference=FixMart.ref();data.submittedAt=new Date().toISOString();FixMart.save(form.dataset.storage||'fixmart_enquiries',data);form.reset();toast(`Thanks — your enquiry is received. Reference: ${data.reference}`)});
  document.addEventListener('click',e=>{const back=e.target.closest('[data-back-top]');if(back)window.scrollTo({top:0,behavior:'smooth'})});
  const observe=()=>{const items=document.querySelectorAll('.reveal:not(.visible)');if(!('IntersectionObserver'in window)){items.forEach(x=>x.classList.add('visible'));return}const io=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add('visible');io.unobserve(x.target)}}),{threshold:.08});items.forEach(x=>io.observe(x))};
  document.addEventListener('DOMContentLoaded',()=>{
    localizeImages();
    const marker=[...document.querySelectorAll('main section')].find(section=>section.querySelector('img[alt="Hardware supplies organised for a busy workshop"]'));
    if(marker)marker.insertAdjacentHTML('beforebegin',`<section class="section-pad bg-white dark:bg-slate-950"><div class="container"><div class="max-w-3xl"><span class="eyebrow">Local know-how, practical supplies</span><h2 class="mt-2 font-display text-3xl font-extrabold text-slate-950 dark:text-white sm:text-4xl">Good hardware help, without the runaround.</h2><p class="mt-4 leading-7 text-slate-600 dark:text-slate-300">Every job has its own list. FixMart makes it easier to find everyday parts, compare useful specifications and get a straight answer from a local shop team.</p></div><div class="mt-8 grid gap-6 border-t border-slate-200 pt-6 dark:border-slate-800 md:grid-cols-3"><article><p class="text-xs font-bold uppercase tracking-widest text-blue-700 dark:text-blue-300">01 · Find your fit</p><h3 class="mt-2 font-display text-lg font-bold text-slate-900 dark:text-white">Sizes and specifications</h3><p class="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">Share the size, material or part you need and ask our team to check suitable options.</p></article><article><p class="text-xs font-bold uppercase tracking-widest text-blue-700 dark:text-blue-300">02 · Get your list ready</p><h3 class="mt-2 font-display text-lg font-bold text-slate-900 dark:text-white">Single items or site needs</h3><p class="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">Browse the everyday range for home repairs, workshops and larger project requirements.</p></article><article><p class="text-xs font-bold uppercase tracking-widest text-blue-700 dark:text-blue-300">03 · Talk to a local team</p><h3 class="mt-2 font-display text-lg font-bold text-slate-900 dark:text-white">Helpful answers nearby</h3><p class="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">Check prices, availability and local delivery by getting in touch with the shop.</p></article></div></div></section>`);
    const reviews=[...document.querySelectorAll('main section')].find(section=>section.querySelector('figure blockquote'));
      if(reviews)reviews.insertAdjacentHTML('beforebegin',`<section class="section-pad bg-slate-100 dark:bg-slate-900/60"><div class="container"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><span class="eyebrow">Made for the work ahead</span><h2 class="mt-2 font-display text-3xl font-extrabold text-slate-950 dark:text-white">A closer look at FixMart.</h2><p class="mt-3 max-w-xl text-slate-600 dark:text-slate-300">From well-stocked benches to the details that finish a job, explore the spaces and supplies behind dependable work.</p></div><a href="products.html" class="font-bold text-blue-700 dark:text-blue-300 py-2">Browse product range →</a></div><div class="mt-7 grid grid-cols-2 gap-3 sm:gap-4 lg:grid-cols-5"><figure class="gallery-card"><img src="assets/images/Small parts, big jobs.jpg" alt="Workshop fasteners and hardware components" loading="lazy"><figcaption>Small parts, big jobs</figcaption></figure><figure class="gallery-card"><img src="assets/images/Tools in hand.jpg" alt="Hand tools ready for workshop use" loading="lazy"><figcaption>Tools in hand</figcaption></figure><figure class="gallery-card"><img src="assets/images/Built to connect.jpg" alt="Plumbing pipes and fittings" loading="lazy"><figcaption>Built to connect</figcaption></figure><figure class="gallery-card"><img src="assets/images/Powering projects.jpg" alt="Electrical fittings and components" loading="lazy"><figcaption>Powering projects</figcaption></figure><figure class="gallery-card"><img src="assets/images/Ready at the workbench.jpg" alt="Hardware arranged on a workshop bench" loading="lazy"><figcaption>Workbench</figcaption></figure></div></div></section>`);
      if(reviews)reviews.insertAdjacentHTML('beforebegin',`<section class="section-pad bg-white dark:bg-slate-950"><div class="container"><div class="grid items-center gap-8 overflow-hidden rounded-2xl bg-blue-50 dark:bg-slate-900 md:grid-cols-2"><div class="p-7 sm:p-10"><span class="eyebrow">For every kind of project</span><h2 class="mt-2 font-display text-3xl font-extrabold text-slate-950 dark:text-white">From the first fix to the finishing touch.</h2><p class="mt-4 leading-7 text-slate-600 dark:text-slate-300">Get the practical supplies that help your next repair, upgrade or build come together. Browse our range and find the right essentials for the job.</p><a href="products.html" class="mt-6 inline-flex rounded-lg bg-blue-700 px-5 py-3 font-bold text-white transition hover:bg-blue-600">Explore products</a></div><img class="h-64 w-full object-cover md:h-full md:min-h-[340px]" src="assets/images/For every kind of project" alt="Tools and supplies ready for a construction project" loading="lazy"></div></div></section>`);
     const gallerySection=document.querySelector('.gallery-card')?.closest('section');if(gallerySection)gallerySection.insertAdjacentHTML('afterend',`<section class="section-pad bg-white dark:bg-slate-950"><div class="container"><div class="overflow-hidden rounded-2xl bg-slate-900 px-6 py-8 text-white dark:bg-slate-800 sm:px-10 sm:py-10"><div class="flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><span class="text-xs font-bold uppercase tracking-widest text-blue-300">A hand with your next project</span><h2 class="mt-2 font-display text-2xl font-extrabold sm:text-3xl">Not sure which part you need?</h2><p class="mt-3 max-w-xl leading-7 text-slate-300">Tell our local team what you’re working on. We can help check sizes, find suitable fittings and confirm availability.</p></div><a href="contact.html" class="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg bg-blue-600 px-5 py-3.5 font-bold text-white transition hover:bg-blue-500">Ask our team<i data-lucide="arrow-right" class="h-4 w-4"></i></a></div></div></div></section>`);
      const projectCta=[...document.querySelectorAll('main section')].find(section=>section.textContent.includes('A hand with your next project'));if(projectCta&&reviews)reviews.after(projectCta);
      localizeImages();document.querySelectorAll('main section').forEach(section=>section.classList.add('reveal'));observe();window.lucide?.createIcons();
  });
  window.addEventListener('load',()=>window.lucide?.createIcons());
})();
