(() => {
  const products=[
    ['Hex Nut – M8','Fasteners','M8, pack of 50','Zinc-plated steel','₹90','Fasteners.jpg','Precision-threaded hex nuts for general assembly and repair work.'],
    ['Hex Bolt – M10 × 50 mm','Fasteners','M10 × 50 mm, pack of 10','Mild steel, zinc plated','₹120','The right fit and fastening.jpg','Hex-head bolts for workshop and construction use.'],
    ['Self Tapping Screw','Fasteners','25 mm, pack of 100','Hardened steel','₹85','Small parts, big jobs.jpg','Sharp-point screws for sheet metal, timber and light fixing.'],
    ['Flat Washer – M10','Fasteners','M10, pack of 100','Galvanised steel','₹75','Fasteners.jpg','Flat washers help distribute load at bolted joints.'],
    ['Masonry Wall Plug','Fasteners','8 mm, pack of 50','Nylon','₹60','for a secure fit.jpg','Expansion plugs for secure fixing into brick and masonry.'],
    ['Wire Nails – 50 mm','Fasteners','50 mm, 1 kg pack','Mild steel','₹110','Small parts, big jobs.jpg','General-purpose wire nails for carpentry and timber fixing.'],
    ['Anchor Bolt – M12','Fasteners','M12 × 100 mm','Zinc-plated steel','Ask for Price','Fasteners.jpg','Heavy-duty anchor bolt for reliable structural fixing.'],
    ['Claw Hammer – 500 g','Tools','500 g head','Forged steel, fibreglass handle','₹320','hand tools.jpg','Balanced claw hammer for carpentry, assembly and home repairs.'],
    ['Screwdriver Set – 6 pc','Tools','6 pieces','Chrome vanadium steel','₹260','Tools in hand.jpg','Slotted and Phillips screwdrivers with comfortable grip handles.'],
    ['Combination Pliers – 8 in','Tools','200 mm / 8 inch','Chrome vanadium steel','₹240','for a work bench.jpg','Gripping, bending and cutting pliers for workshop and electrical jobs.'],
    ['Adjustable Spanner – 10 in','Tools','250 mm / 10 inch','Drop-forged steel','Ask for Price','hand tools.jpg','Wide-jaw adjustable spanner for plumbing and general fitting.'],
    ['Measuring Tape – 5 m','Tools','5 m, metric scale','ABS case, steel blade','₹140','Tools in hand.jpg','Compact lockable tape for site measurements and workshop tasks.'],
    ['Hacksaw Frame – 12 in','Tools','300 mm blade','Steel frame','₹190','for a work bench.jpg','Adjustable hacksaw for cutting metal, pipe and general materials.'],
    ['Workshop Tool Kit','Tools','Set of assorted hand tools','Alloy steel','Ask for Price','Ready at the workbench.jpg','Useful selection of tools for maintenance and regular workshop jobs.'],
    ['Pipe Wrench – 14 in','Tools','350 mm / 14 inch','Forged steel','₹480','Tools for the next repair.jpg','Strong adjustable pipe wrench for plumbing and service work.'],
    ['PVC Elbow – 90°','Plumbing','25 mm','uPVC','₹18','plumbing fittings.jpg','Smooth-bore 90-degree elbow for PVC plumbing lines.'],
    ['PVC Tee – 25 mm','Plumbing','25 mm','uPVC','₹22','Reliable fittings and connections.jpg','Three-way tee fitting for branching water supply lines.'],
    ['Ball Valve – ½ inch','Plumbing','15 mm / ½ inch','Brass','₹185','Built to connect.jpg','Quarter-turn brass ball valve for water flow control.'],
    ['PVC Connector – 25 mm','Plumbing','25 mm socket','uPVC','₹14','plumbing fittings.jpg','Straight socket connector for joining compatible PVC pipes.'],
    ['Compression Fitting','Plumbing','15 mm','Brass','Ask for Price','Reliable fittings and connections.jpg','Compression fitting for neat, secure pipe connections.'],
    ['Pipe Repair Kit','Plumbing','Multi-size kit','PVC and rubber','Ask for Price','plumbing fittings.jpg','Practical repair components for common plumbing maintenance.'],
    ['Pipe Spanner Set','Plumbing','2-piece set','Forged steel','₹620','Tools in hand.jpg','Pair of wrenches for tightening and loosening pipe fittings.'],
    ['Modular Switch – 6A','Electrical','6A, 1-way','Polycarbonate','₹65','electrial items','Durable modular switch for residential and commercial installations.'],
    ['Copper Wire – 1.5 sq mm','Electrical','90 m coil','FR PVC insulated copper','Ask for Price','Powering projects.jpg','Flexible flame-retardant copper wire for indoor wiring.'],
    ['PVC Electrical Conduit','Electrical','20 mm, 3 m length','Heavy-duty PVC','₹48','electrial items','Rigid conduit pipe to protect and route electrical wiring.'],
    ['Electrical Connector Block','Electrical','12-way, 6 sq mm','Polycarbonate and brass','₹38','electrial items','Insulated terminal strip for secure low-voltage connections.'],
    ['Electrical Hand Tool Set','Electrical','Set of 5','Insulated steel tools','Ask for Price','Powering projects.jpg','Everyday insulated tools for electrical installation work.'],
    ['Cable Ties – 200 mm','Electrical','Pack of 100','Nylon','₹75','electrial items','Cable ties for bundling and organising wiring runs.'],
    ['Cable Gland – 20 mm','Electrical','20 mm','Nylon','₹25','electrial items','Cable entry gland for securing cable into equipment enclosures.'],
    ['Electrical Junction Box','Electrical','4-way, surface mount','PVC','₹55','Powering projects.jpg','Compact junction box for protected wire connections.'],
    ['Insulation Tape','Electrical','18 mm × 10 m','PVC','₹22','electrial items','General-purpose electrical insulation tape for wiring work.'],
    ['Multimeter – Digital','Electrical','Auto range','ABS body','Ask for Price','Powering projects.jpg','Digital meter for basic voltage, resistance and continuity checks.'],
    ['Workshop Bench Tools','Tools','Assorted selection','Steel','Ask for Price','Ready at the workbench.jpg','Workshop staples for fitting, repair and maintenance tasks.'],
    ['Industrial Tool Set','Tools','Assorted set','Alloy steel','Ask for Price','Tools in hand.jpg','A practical selection of workshop tools for regular maintenance.'],
    ['Metalworking Clamp','Tools','Medium duty','Cast iron','₹520','for a work bench.jpg','Bench clamp for holding work securely during cutting and fitting.'],
    ['Power Tool Accessory Kit','Tools','Multi-piece','Steel and carbide','Ask for Price','Tools for the next repair.jpg','Workshop accessories for drilling, fastening and repair tasks.'],
    ['Technician Tool Bag','Tools','16 inch','Reinforced fabric','₹390','Ready at the workbench.jpg','Portable tool bag for carrying daily service and installation essentials.']
  ].map((p,i)=>({id:i,name:p[0],category:p[1],spec:p[2],material:p[3],price:p[4],stock:'Available',image:`assets/images/${p[5]}`,description:p[6],variants:['Standard pack','Bulk pack']})).filter(p=>['Hex Nut – M8','Hex Bolt – M10 × 50 mm','Self Tapping Screw','Claw Hammer – 500 g','Screwdriver Set – 6 pc','Combination Pliers – 8 in','PVC Elbow – 90°','PVC Tee – 25 mm','Ball Valve – ½ inch','Modular Switch – 6A','Copper Wire – 1.5 sq mm','PVC Electrical Conduit'].includes(p.name));
  const grid=document.querySelector('[data-products-grid]');if(!grid)return;
  grid.closest('section')?.insertAdjacentHTML('afterend',`<section class="section-pad bg-blue-50 dark:bg-slate-900/60"><div class="container"><div class="mx-auto max-w-3xl text-center"><span class="eyebrow">Need help choosing?</span><h2 class="mt-2 font-display text-3xl font-extrabold text-slate-950 dark:text-white">Find the right fit for your project.</h2><p class="mt-3 leading-7 text-slate-600 dark:text-slate-300">Share the product name, size or a photo with our local team. We can help check suitable options and current availability.</p><a href="contact.html" class="mt-6 inline-flex items-center gap-2 rounded-lg bg-blue-700 px-5 py-3 font-bold text-white transition hover:bg-blue-800">Ask our team<i data-lucide="arrow-right" class="h-4 w-4"></i></a></div></div></section>`);
  const search=document.querySelector('[data-product-search]'),filter=document.querySelector('[data-category-filter]'),sort=document.querySelector('[data-product-sort]');
  const params=new URLSearchParams(location.search),prefs=JSON.parse(localStorage.getItem('fixmart_preferences')||'{}');
  let chosen=params.get('category')||prefs.category||'All';
  if(filter)filter.value=chosen;if(sort&&prefs.sort)sort.value=prefs.sort;if(search)search.value=params.get('q')||'';
  function render(){
    let list=products.filter(p=>(chosen==='All'||p.category===chosen)&&(`${p.name} ${p.category} ${p.spec} ${p.material}`).toLowerCase().includes((search?.value||'').toLowerCase()));
    if(sort?.value==='name')list.sort((a,b)=>a.name.localeCompare(b.name));
    if(sort?.value==='price')list.sort((a,b)=>(parseInt(a.price.replace(/\D/g,''))||99999)-(parseInt(b.price.replace(/\D/g,''))||99999));
    grid.innerHTML=list.length?list.map(p=>`<article class="product-card flex h-full flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><img class="product-image w-full bg-slate-100 dark:bg-slate-800" src="${p.image}" alt="${p.name}" loading="lazy"><div class="flex flex-1 flex-col p-5"><div class="flex items-center justify-between gap-2"><span class="rounded-full bg-orange-50 px-2.5 py-1 text-xs font-bold text-orange-700 dark:bg-orange-950 dark:text-orange-300">${p.category}</span><span class="text-xs font-semibold text-emerald-700 dark:text-emerald-400">● ${p.stock}</span></div><h3 class="mt-3 font-display text-lg font-bold text-slate-900 dark:text-white">${p.name}</h3><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">${p.spec} · ${p.material}</p><div class="mt-auto pt-4"><div class="flex items-center justify-between"><strong class="text-lg text-slate-900 dark:text-white">${p.price}</strong><a href="contact.html?product=${encodeURIComponent(p.name)}" class="py-2 text-xs font-semibold text-orange-700 dark:text-orange-400">Enquire</a></div><button data-product-details="${p.id}" class="mt-4 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm font-bold text-slate-800 hover:border-orange-500 hover:text-orange-700 dark:border-slate-700 dark:text-slate-200">View Details</button></div></div></article>`).join(''):'<p class="col-span-full rounded-xl bg-white p-8 text-center text-slate-600 dark:bg-slate-900 dark:text-slate-300">No products match. Try another search or category.</p>';
    window.lucide?.createIcons();
  }
  search?.addEventListener('input',render);
  filter?.addEventListener('change',()=>{chosen=filter.value;localStorage.setItem('fixmart_preferences',JSON.stringify({...prefs,category:chosen}));render()});
  sort?.addEventListener('change',()=>{localStorage.setItem('fixmart_preferences',JSON.stringify({...prefs,sort:sort.value}));render()});render();
  document.addEventListener('click',e=>{const btn=e.target.closest('[data-product-details]');if(!btn)return;const p=products[Number(btn.dataset.productDetails)],modal=document.querySelector('[data-product-modal]');modal.innerHTML=`<div class="relative m-auto max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white shadow-2xl dark:bg-slate-900"><button data-modal-close class="absolute right-3 top-3 z-10 grid h-10 w-10 place-items-center rounded-full bg-white/90 text-slate-800 shadow" aria-label="Close"><i data-lucide="x"></i></button><div class="grid md:grid-cols-2"><img src="${p.image}" alt="${p.name}" class="h-56 w-full object-cover md:h-full"><div class="p-6 sm:p-8"><span class="eyebrow">${p.category}</span><h2 class="mt-2 font-display text-2xl font-extrabold text-slate-900 dark:text-white">${p.name}</h2><p class="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-300">${p.description}</p><dl class="mt-5 grid grid-cols-[100px_1fr] gap-3 text-sm"><dt class="text-slate-500">Size</dt><dd class="font-semibold text-slate-800 dark:text-slate-200">${p.spec}</dd><dt class="text-slate-500">Material</dt><dd class="font-semibold text-slate-800 dark:text-slate-200">${p.material}</dd><dt class="text-slate-500">Variants</dt><dd class="font-semibold text-slate-800 dark:text-slate-200">${p.variants.join(', ')}</dd><dt class="text-slate-500">Price</dt><dd class="font-bold text-blue-700 dark:text-blue-300">${p.price}</dd></dl><a href="contact.html?product=${encodeURIComponent(p.name)}" class="mt-7 inline-flex w-full justify-center rounded-lg bg-blue-700 px-4 py-3 font-bold text-white hover:bg-blue-800">Enquire about this product</a></div></div></div>`;modal.classList.add('modal-open');modal.setAttribute('aria-hidden','false');document.body.classList.add('no-scroll');window.lucide?.createIcons()});
  document.addEventListener('click',e=>{if(e.target.matches('[data-modal-close]')||e.target.matches('[data-product-modal]')){const modal=document.querySelector('[data-product-modal]');modal.classList.remove('modal-open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('no-scroll')}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){const modal=document.querySelector('[data-product-modal]');modal?.classList.remove('modal-open');document.body.classList.remove('no-scroll')}});
})();
